apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: scope-dashboard
  namespace: weave
  annotations:
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: scope.internal.peviwatt.io
    http:
      paths:
      - path: /
        backend:
          serviceName: weave-scope-app
          servicePort: 80
